update build

diff --git a/robohustler/usr/local/configs/aliasfile b/robohustler/usr/local/configs/aliasfile
--- a/robohustler/usr/local/configs/aliasfile
+++ b/robohustler/usr/local/configs/aliasfile
@@ -97,6 +97,56 @@ drive(){
     rqt_plot /SwarmbotPlcController/drive_velocity_command /SwarmbotPlcController/hardware_responses/wheel_linear_vel_average /SwarmbotLocalisation/gps/fix/velocities/ground
 }
 
+logdir() {
+    # Function to pad an argument with leading zeros to make it 4 characters in length
+    pad_to_4_digits() {
+        local arg="$1"
+        printf "%04d" "$arg"
+    }
+
+    # Function to convert all characters to uppercase if "can" is passed in
+    convert_to_uppercase() {
+        local arg="$1"
+        if [ "$arg" = "can" ]; then
+            arg=$(echo "$arg" | tr '[:lower:]' '[:upper:]')
+        fi
+        echo "$arg"
+    }
+
+    # Function to display the help menu
+    show_help() {
+        echo "Usage: logdir <robotno> <ticketno> <datadir>"
+        echo "logdir 20 4094"
+        echo "will get you"
+        echo " robot:sb20 ticket:4094 data:CAN"
+    }
+
+    # Check for the help option
+    if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
+        show_help
+        return 0
+    fi
+
+    # Check for the correct number of arguments
+    if [ "$#" -ne 3 ]; then
+        echo "Error: Missing arguments."
+        show_help
+        return 1
+    fi
+
+    local log_dir="$HOME/logs/sb-$(pad_to_4_digits "$1")/$2/$(convert_to_uppercase "$3")"
+
+    # Check if the directory exists
+    if [ -d "$log_dir" ]; then
+        cd "$log_dir" || return 1
+        log_dir=$(realpath "$log_dir")
+        echo "Changed to: $log_dir"
+    else
+        echo "Error: Directory does not exist."
+        return 1
+    fi
+}
+
 reload(){
 
 read -r -p "Press Enter to continue or Ctrl+C to cancel...you will lose your current terminal if you continue" userInput
