update build

diff --git a/robohustler/DEBIAN/postinst b/robohustler/DEBIAN/postinst
--- a/robohustler/DEBIAN/postinst
+++ b/robohustler/DEBIAN/postinst
@@ -6,6 +6,21 @@ function handle_exit {
     exit 0
 }
 
+while true; do
+    read -p "If you proceed your terminal will close when finished - (proceed/exit): " user_input
+    # Convert user input to lowercase for case-insensitive comparison
+    user_input_lc=$(echo "$user_input" | tr '[:upper:]' '[:lower:]')
+    if [ "$user_input_lc" == "proceed" ]; then
+        echo "Continuing..."
+        break
+    elif [ "$user_input_lc" == "exit" ]; then
+        echo "Exiting..."
+        exit 1
+    else
+        echo "Invalid input. Please type 'proceed' or 'exit'."
+    fi
+done
+
 # Set the path to aliasfile relative to package root
 aliasfile_path="./usr/local/configs/aliasfile"
 percep_path="./usr/local/configs/perception.rviz"
@@ -16,6 +31,8 @@ search_string="export ZT_IP=<zerotier.ip>"
 
 # Get the user's home directory
 user_home_dir="$HOME"
+
+alias_content=$(cat "$aliasfile_path")
 
 # Check if .bash_aliases exists and does NOT contain the search string
 if [ -f "$user_home_dir/.bash_aliases" ] || ! grep -q "$search_string" "$user_home_dir/.bash_aliases"; then
@@ -86,3 +103,4 @@ echo "Installation completed!"
 echo "Welcome to robo hustler!"
 echo "Next time you open a terminal just type howdoi followed by a keyword"
 echo "Alternatively type how to for a full usage list"
+echo "This process is complete. Close terminal, open command prompt, type "wsl --shutdown" and press enter"
