update build

diff --git a/robohustler/DEBIAN/postinst b/robohustler/DEBIAN/postinst
--- a/robohustler/DEBIAN/postinst
+++ b/robohustler/DEBIAN/postinst
@@ -7,34 +7,24 @@ function handle_exit {
 }
 
 while true; do
-  read -p "If you proceed your terminal will close when finished - (proceed/exit): " user_input
-  # Convert user input to lowercase for case-insensitive comparison
-  user_input_lc=$(echo "$user_input" | tr '[:upper:]' '[:lower:]')
-  if [ "$user_input_lc" == "proceed" ]; then
-    echo "Continuing..."
-    break
-  elif [ "$user_input_lc" == "exit" ]; then
-    echo "Exiting..."
-    exit 1
-  else
-    echo "Invalid input. Please type 'proceed' or 'exit'."
-  fi
+    read -p "If you proceed your terminal will close when finished - (proceed/exit): " user_input
+    # Convert user input to lowercase for case-insensitive comparison
+    user_input_lc=$(echo "$user_input" | tr '[:upper:]' '[:lower:]')
+    if [ "$user_input_lc" == "proceed" ]; then
+        echo "Continuing..."
+        break
+    elif [ "$user_input_lc" == "exit" ]; then
+        echo "Exiting..."
+        exit 1
+    else
+        echo "Invalid input. Please type 'proceed' or 'exit'."
+    fi
 done
 
 # Set the path to aliasfile relative to package root
 aliasfile_path="./usr/local/configs/aliasfile"
 percep_path="./usr/local/configs/perception.rviz"
 binaries_path="./usr/local/scripts/"
-
-# Function to handle exit
-handle_exit() {
-    echo "Exiting..."
-    exit 1
-}
-
-logged_in_user="$SUDO_USER"
-
-alias_content=$(cat "$aliasfile_path")
 
 # Define the string to search for
 search_string="export ZT_IP=<zerotier.ip>"
@@ -60,8 +50,11 @@ if [ -f "$user_home_dir/.bash_aliases" ] && ! grep -q "$search_string" "$user_ho
     done
 
     # Replace ZeroTier IP placeholder in the alias content
-    alias_content=$(echo "$alias_content" | sed "s/<zerotier.ip>/$zerotier_ip/g")
+    alias_content=$(cat "$aliasfile_path" | sed "s/<zerotier.ip>/$zerotier_ip/g")
 fi
+
+# Rest of your script...
+
 
 
 user_home="/home/$logged_in_user"
